backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "blog/.vuepress/public/img"
public_folder: "/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About"
        file: "blog/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
          - {label: "Content", name: "body", widget: "markdown"}
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "blog/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Tags", name: "tags" , widget: "list", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}